
build:linux:
  image: "rust:latest"
  before_script:
  - apt-get update && apt-get -y install cmake
  - rustup toolchain add stable
  script:
  - cargo +stable build

build:redox:
  image: "redoxos/redoxer"
  script:
  - redoxer build

build:no_std:
  image: "rust:latest"
  before_script:
  - rustup toolchain add stable --target thumbv6m-none-eabi
  script:
  - cargo +stable build --no-default-features --features=no-std --target thumbv6m-none-eabi
